using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using IkeMtz.NRSRx.Core.Models;

namespace Mechanager.Inventory.Models
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class PartVendor
  : IIdentifiable, IAuditable
  {
    public PartVendor()
    {
      Transactions = new HashSet<Transaction>();
    }

    [Required]
    public Guid Id { get; set; }
    [Required]
    public Guid PartId { get; set; }
    [Required]
    public Guid VendorId { get; set; }
    [Required]
    [MaxLength(50)]
    public string Barcode { get; set; }
    [Required]
    public decimal Cost { get; set; }
    [Required]
    [MaxLength(4)]
    public string TenantId { get; set; }
    [Required]
    [MaxLength(250)]
    public string CreatedBy { get; set; }
    [MaxLength(250)]
    public string UpdatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
    public virtual Part Part { get; set; }
    public virtual Vendor Vendor { get; set; }
    public virtual ICollection<Transaction> Transactions { get; }
  }
}
