using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using IkeMtz.NRSRx.Core.Models;

namespace Mechanager.Inventory.Models
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Part
  : IIdentifiable, IAuditable
  {
    public Part()
    {
      PartVendors = new HashSet<PartVendor>();
      Transactions = new HashSet<Transaction>();
    }

    [Required]
    public Guid Id { get; set; }
    [Required]
    [MaxLength(25)]
    public string ManufacturerId { get; set; }
    [Required]
    [MaxLength(250)]
    public string Description { get; set; }
    [Required]
    [MaxLength(5)]
    public string Location { get; set; }
    public decimal? Price { get; set; }
    [Required]
    public decimal CurrentQuantity { get; set; }
    [Required]
    public decimal MinThreshold { get; set; }
    [Required]
    public decimal ReplenishAmount { get; set; }
    public DateTimeOffset? LastSold { get; set; }
    [Required]
    public Guid StoreId { get; set; }
    [Required]
    public bool IsEnabled { get; set; }
    [Required]
    [MaxLength(4)]
    public string TenantId { get; set; }
    [Required]
    [MaxLength(250)]
    public string CreatedBy { get; set; }
    [MaxLength(250)]
    public string UpdatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
    public virtual ICollection<PartVendor> PartVendors { get; }
    public virtual ICollection<Transaction> Transactions { get; }
  }
}
