using System;
using System.ComponentModel.DataAnnotations;
using IkeMtz.NRSRx.Core.Models;

namespace Mechanager.Inventory.Models
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Transaction
  : IIdentifiable, IAuditable
  {
    [Required]
    public Guid Id { get; set; }
    [Required]
    public Guid PartId { get; set; }
    public Guid? VendorId { get; set; }
    public Guid? PartVendorId { get; set; }
    [Required]
    public decimal Amount { get; set; }
    [Required]
    public Guid StoreId { get; set; }
    [Required]
    [MaxLength(250)]
    public string CreatedBy { get; set; }
    [MaxLength(250)]
    public string UpdatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
    public virtual Part Part { get; set; }
    public virtual Vendor Vendor { get; set; }
    public virtual PartVendor PartVendor { get; set; }
  }
}
