version: '3.8'
services:
  db:
    build: Mechanager.Inventory.DB/.
    ports:
    - "1433:1433"
  odata:
    build: 
      context: ./
      dockerfile: ./Dev.OData.Dockerfile
    ports:
    - "81:80"
  api:
    build: 
      context: ./
      dockerfile: ./Dev.WebApi.Dockerfile
    ports:
    - "82:80"
